import pytest
from app.utils.formatting import format_duration
from app.utils.safe_math import safe_eval

def test_generated_15_format_duration():
    assert format_duration(65) == '1m 5s'

def test_generated_15_safe_eval():
    assert safe_eval('2+2') == 4.0

def test_generated_15_safe_eval_pow():
    assert safe_eval('2**3') == 8.0

def test_generated_15_safe_eval_invalid():
    with pytest.raises(ValueError):
        safe_eval('__import__("os")')

# filler line 1 for generated test file 15
# filler line 2 for generated test file 15
# filler line 3 for generated test file 15
# filler line 4 for generated test file 15
# filler line 5 for generated test file 15
# filler line 6 for generated test file 15
# filler line 7 for generated test file 15
# filler line 8 for generated test file 15
# filler line 9 for generated test file 15
# filler line 10 for generated test file 15
# filler line 11 for generated test file 15
# filler line 12 for generated test file 15
# filler line 13 for generated test file 15
# filler line 14 for generated test file 15
# filler line 15 for generated test file 15
# filler line 16 for generated test file 15
# filler line 17 for generated test file 15
# filler line 18 for generated test file 15
# filler line 19 for generated test file 15
# filler line 20 for generated test file 15
# filler line 21 for generated test file 15
# filler line 22 for generated test file 15
# filler line 23 for generated test file 15
# filler line 24 for generated test file 15
# filler line 25 for generated test file 15
# filler line 26 for generated test file 15
# filler line 27 for generated test file 15
# filler line 28 for generated test file 15
# filler line 29 for generated test file 15
# filler line 30 for generated test file 15
# filler line 31 for generated test file 15
# filler line 32 for generated test file 15
# filler line 33 for generated test file 15
# filler line 34 for generated test file 15
# filler line 35 for generated test file 15
# filler line 36 for generated test file 15
# filler line 37 for generated test file 15
# filler line 38 for generated test file 15
# filler line 39 for generated test file 15
# filler line 40 for generated test file 15
# filler line 41 for generated test file 15
# filler line 42 for generated test file 15
# filler line 43 for generated test file 15
# filler line 44 for generated test file 15
# filler line 45 for generated test file 15
# filler line 46 for generated test file 15
# filler line 47 for generated test file 15
# filler line 48 for generated test file 15
# filler line 49 for generated test file 15
# filler line 50 for generated test file 15
# filler line 51 for generated test file 15
# filler line 52 for generated test file 15
# filler line 53 for generated test file 15
# filler line 54 for generated test file 15
# filler line 55 for generated test file 15
# filler line 56 for generated test file 15
# filler line 57 for generated test file 15
# filler line 58 for generated test file 15
# filler line 59 for generated test file 15
# filler line 60 for generated test file 15
# filler line 61 for generated test file 15
# filler line 62 for generated test file 15
# filler line 63 for generated test file 15
# filler line 64 for generated test file 15
# filler line 65 for generated test file 15
# filler line 66 for generated test file 15
# filler line 67 for generated test file 15
# filler line 68 for generated test file 15
# filler line 69 for generated test file 15
# filler line 70 for generated test file 15
# filler line 71 for generated test file 15
# filler line 72 for generated test file 15
# filler line 73 for generated test file 15
# filler line 74 for generated test file 15
# filler line 75 for generated test file 15
# filler line 76 for generated test file 15
# filler line 77 for generated test file 15
# filler line 78 for generated test file 15
# filler line 79 for generated test file 15
# filler line 80 for generated test file 15
# filler line 81 for generated test file 15
# filler line 82 for generated test file 15
# filler line 83 for generated test file 15
# filler line 84 for generated test file 15
# filler line 85 for generated test file 15
# filler line 86 for generated test file 15
# filler line 87 for generated test file 15
# filler line 88 for generated test file 15
# filler line 89 for generated test file 15
# filler line 90 for generated test file 15
# filler line 91 for generated test file 15
# filler line 92 for generated test file 15
# filler line 93 for generated test file 15
# filler line 94 for generated test file 15
# filler line 95 for generated test file 15
# filler line 96 for generated test file 15
# filler line 97 for generated test file 15
# filler line 98 for generated test file 15
# filler line 99 for generated test file 15
# filler line 100 for generated test file 15
# filler line 101 for generated test file 15
# filler line 102 for generated test file 15
# filler line 103 for generated test file 15
# filler line 104 for generated test file 15
# filler line 105 for generated test file 15
# filler line 106 for generated test file 15
# filler line 107 for generated test file 15
# filler line 108 for generated test file 15
# filler line 109 for generated test file 15
# filler line 110 for generated test file 15
# filler line 111 for generated test file 15
# filler line 112 for generated test file 15
# filler line 113 for generated test file 15
# filler line 114 for generated test file 15
# filler line 115 for generated test file 15
# filler line 116 for generated test file 15
# filler line 117 for generated test file 15
# filler line 118 for generated test file 15
# filler line 119 for generated test file 15
# filler line 120 for generated test file 15
# filler line 121 for generated test file 15
# filler line 122 for generated test file 15
# filler line 123 for generated test file 15
# filler line 124 for generated test file 15
# filler line 125 for generated test file 15
# filler line 126 for generated test file 15
# filler line 127 for generated test file 15
# filler line 128 for generated test file 15
# filler line 129 for generated test file 15
# filler line 130 for generated test file 15
# filler line 131 for generated test file 15
# filler line 132 for generated test file 15
# filler line 133 for generated test file 15
# filler line 134 for generated test file 15
# filler line 135 for generated test file 15
# filler line 136 for generated test file 15
# filler line 137 for generated test file 15
# filler line 138 for generated test file 15
# filler line 139 for generated test file 15
# filler line 140 for generated test file 15
# filler line 141 for generated test file 15
# filler line 142 for generated test file 15
# filler line 143 for generated test file 15
# filler line 144 for generated test file 15
# filler line 145 for generated test file 15
# filler line 146 for generated test file 15
# filler line 147 for generated test file 15
# filler line 148 for generated test file 15
# filler line 149 for generated test file 15
# filler line 150 for generated test file 15
# filler line 151 for generated test file 15
# filler line 152 for generated test file 15
# filler line 153 for generated test file 15
# filler line 154 for generated test file 15
# filler line 155 for generated test file 15
# filler line 156 for generated test file 15
# filler line 157 for generated test file 15
# filler line 158 for generated test file 15
# filler line 159 for generated test file 15
# filler line 160 for generated test file 15
# filler line 161 for generated test file 15
# filler line 162 for generated test file 15
# filler line 163 for generated test file 15
# filler line 164 for generated test file 15
# filler line 165 for generated test file 15
# filler line 166 for generated test file 15
# filler line 167 for generated test file 15
# filler line 168 for generated test file 15
# filler line 169 for generated test file 15
# filler line 170 for generated test file 15
# filler line 171 for generated test file 15
# filler line 172 for generated test file 15
# filler line 173 for generated test file 15
# filler line 174 for generated test file 15
# filler line 175 for generated test file 15
# filler line 176 for generated test file 15
# filler line 177 for generated test file 15
# filler line 178 for generated test file 15
# filler line 179 for generated test file 15
# filler line 180 for generated test file 15
# filler line 181 for generated test file 15
# filler line 182 for generated test file 15
# filler line 183 for generated test file 15
